name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create config.json
        run: |
          echo '{
            "githubOwner": "${{ secrets.VITE_GITHUB_OWNER }}",
            "githubRepo": "${{ secrets.VITE_GITHUB_REPO }}",
            "githubToken": "${{ secrets.VITE_GITHUB_TOKEN }}"
          }' > dist/config.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
